### ISSUE TITLE
Webcrypto import errors in 0.29.1

### ISSUE THREAD

**Issue by bgins** [fission-suite/webnative#318] opened 2021-10-29 18:40 UTC
# Summary

## Problem

`webcrypto` cannot be imported or is `undefined` with some bundlers/build tools with webnative `0.29.1`.

### Impact

Some applications will not be able to use webnative at `0.29.1`, depending on the build system or bundler they use if any.

## Solution

Unknown. The issue appears to be related to the change over to `one-webcrypto` and there may be something we can change there.

# Detail

**Describe the bug**

Parcel 2, Webpack 5, and Create React App report errors in the console. (See the screenshots below.)

**To Reproduce**
1. Clone https://github.com/fission-suite/react-todomvc
2. Upgrade webnative to 0.29.1 on each branch
3. `npm start` for local dev and `npm run build` for a build in each
3. Vite should work, but the `parcel`, `webpack`, and `main` branches should fail (main is CRA)

**Expected behavior**

No errors in the console. The app works and can do TodoMVC things.

**Screenshots**

CRA local development

<img width="960" alt="cra-dev" src="https://user-images.githubusercontent.com/7957636/139485300-b0d12df3-9698-4c69-a50c-6f22955c4599.png">

CRA build (fails at build time)

<img width="960" alt="cra-build" src="https://user-images.githubusercontent.com/7957636/139485374-0ba45219-e5ca-484c-b523-4d72f6acbc7b.png">

Parcel 2 local development

<img width="960" alt="parcel-dev" src="https://user-images.githubusercontent.com/7957636/139485405-e74ae28b-c17b-4250-94fc-43b0491f6521.png">

Parcel 2 build

<img width="960" alt="parcel-build" src="https://user-images.githubusercontent.com/7957636/139485426-64d06dfc-4395-477b-ae2d-3b1bed27ca51.png">

Webpack 5 local development and build

<img width="937" alt="webpack-dev-and-build" src="https://user-images.githubusercontent.com/7957636/139485497-a3700267-cc45-4694-9fa5-4f13f632162c.png">

**Comment by matheus23** [comment] 2021-11-02 10:31
I'm able to fix issues with parcel and webpack with this commit: https://github.com/fission-suite/one-webcrypto/commit/a95b889887ffa557cdaddd2f19cc14a4bec79e56

CRA remains a problem. I'm not sure why it can't import webcrypto at all :zany_face:

**Comment by matheus23** [comment] 2021-11-02 10:55
"Progress" on CRA:

Directly importing `one-webcrypto` doesn't work as well (so the issue is not related to a dependency chain like react-todomvc -> webnative -> one-webcrypto, but also happens with react-todomvc -> one-webcrypto).

Importing files within one-webcrypto seems to fix the issue. That is:
* `import { webcrypto } from "one-webcrypto"` fails with "Attempted import error: 'webcrypto' is not exported from 'one-webcrypto'."
* `import { webcrypto } from "one-webcrypto/dynamic.cjs"` fails with an error unrelated to this line
* `import { webcrypto } from "one-webcrypto/node.cjs"` fails with an error unrelated to this line
* `import { webcrypto } from "one-webcrypto/node.mjs"` fails with an error unrelated to this line
* `import { webcrypto } from "one-webcrypto/browser.mjs"` fails with an error unrelated to this line

So it seems like react-scripts just fail to resolve the correct file given `one-webcrypto`. I have *no* clue what could cause this. Esp, since if it did resolve *anything* it would work fine, and it surely isn't package exports related, since we're including *both* an `exports` field and a `main` field in `one-webcrypto/package.json`.

**Comment by matheus23** [comment] 2021-11-02 11:07
Okay, more updates. I removed the `import "webnative"` imports temporarily (leaving all other code & disabling eslint).

Then I added various forms of `one-webcrypto` imports to see whether CRA can import them:

* :x: `import { webcrypto } from "one-webcrypto"` fails with "Attempted import error: 'webcrypto' is not exported from 'one-webcrypto'."
* :x: `import { webcrypto } from "one-webcrypto/dynamic.cjs"` fails with "Attempted import error: 'webcrypto' is not exported from 'one-webcrypto/dynamic.cjs'."
* :x: `import { webcrypto } from "one-webcrypto/node.cjs"` fails with "Attempted import error: 'webcrypto' is not exported from 'one-webcrypto/node.cjs'."
* :white_check_mark: `import { webcrypto } from "one-webcrypto/node.mjs"`
* :white_check_mark: `import { webcrypto } from "one-webcrypto/browser.mjs"`
* :x: `import * as oneWC from "one-webcrypto"` fails with "Attempted import error: 'webcrypto' is not exported from 'one-webcrypto' (imported as 'oneWC')." (?????)
* :white_check_mark: `import oneWC from "one-webcrypto"` works ????? although it shouldn't?

When I run this:
```js
import oneWC from "one-webcrypto"

console.log(oneWC)
```
It just prints `/static/media/dynamic.30e18fbe.cjs` to the console. So `oneWC` is initialised to a string :raised_eyebrow:

**Comment by matheus23** [comment] 2021-11-02 11:56
Since `react-scripts` uses webpack 4, I've tried to get the `webpack` branch with webpack downgraded to version 4 working.
However, webpack 4's version of acornjs (the javascript parser they use) doesn't understand `export * as X from "..."` syntax that's used in webnative.

`react-scripts` probably uses babeljs liberally to transpile the javascript down so that it can be understood by webpack 4. I haven't been able to get that working.

---

I really want to get 0.29.1 out there, and I still think one-webcrypto is an improvement over what we had before, because now we can use parts of keystore-idb and webnative in nodejs and it might open the door for sveltekit. It also makes it easier for new libraries (e.g. ucans) to adopt webcrypto in a way such that they're already quite "isomorphic" out of the box and in the future we can change one-webcrypto in one place and everyone benefits.
The big downside is not supporting CRA anymore. :confused: 

What do you think?

**Comment by bgins** [comment] 2021-11-02 15:56
I think the benefits outweigh support for CRA. A future release of CRA might use webpack 5 or another bundler, and we could re-evaluate it then. 

Create React App is [by their own admission](https://github.com/facebook/create-react-app/issues/11180#issuecomment-874748552) slow to release new versions. In the meantime, we can recommend Vite, Parcel, and Webpack 5, and we have good examples of how to migrate from CRA to these bundlers in the [React TodoMVC](https://github.com/fission-suite/react-todomvc) repository.

**Comment by bgins** [comment] 2021-11-02 15:58
I may have prematurely closed this issue, because we may need a new version of `one-webcrypto`! Feel free to close it if we are good to go.

**Comment by matheus23** [comment] 2021-11-02 16:09
We have a new version of `one-webcrypto`: `1.0.3`. I've already released it.
We need to merge PRs to upgrade the one-webcrypto version into `keystore-idb` and `webnative`, though.
Here's the one for keystore-idb: https://github.com/fission-suite/keystore-idb/pull/61
I'm waiting to merge&release that one so that we can get that into webnative.

**Comment by bgins** [comment] 2021-11-05 21:51
https://github.com/fission-suite/webnative/pull/321 fixes the webcrypto import errors. 

Turns out the Webpack error was something else. Documented it in a new issue: https://github.com/fission-suite/webnative/issues/323

**Comment by matheus23** [comment] 2021-11-12 10:52
Closing this, because #321 is merged now.

**Closed by matheus23** 2021-11-12 10:52 UTC
Labels: bug
